// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: findmaxpb/findmax.proto

//package name

package findmaxpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// FindMax Request
type FindMaxRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Num int32 `protobuf:"varint,1,opt,name=num,proto3" json:"num,omitempty"`
}

func (x *FindMaxRequest) Reset() {
	*x = FindMaxRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_findmaxpb_findmax_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindMaxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindMaxRequest) ProtoMessage() {}

func (x *FindMaxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_findmaxpb_findmax_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindMaxRequest.ProtoReflect.Descriptor instead.
func (*FindMaxRequest) Descriptor() ([]byte, []int) {
	return file_findmaxpb_findmax_proto_rawDescGZIP(), []int{0}
}

func (x *FindMaxRequest) GetNum() int32 {
	if x != nil {
		return x.Num
	}
	return 0
}

// FindMax Response
type FindMaxResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result int32 `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *FindMaxResponse) Reset() {
	*x = FindMaxResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_findmaxpb_findmax_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindMaxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindMaxResponse) ProtoMessage() {}

func (x *FindMaxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_findmaxpb_findmax_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindMaxResponse.ProtoReflect.Descriptor instead.
func (*FindMaxResponse) Descriptor() ([]byte, []int) {
	return file_findmaxpb_findmax_proto_rawDescGZIP(), []int{1}
}

func (x *FindMaxResponse) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

var File_findmaxpb_findmax_proto protoreflect.FileDescriptor

var file_findmaxpb_findmax_proto_rawDesc = []byte{
	0x0a, 0x17, 0x66, 0x69, 0x6e, 0x64, 0x6d, 0x61, 0x78, 0x70, 0x62, 0x2f, 0x66, 0x69, 0x6e, 0x64,
	0x6d, 0x61, 0x78, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x66, 0x69, 0x6e, 0x64, 0x6d,
	0x61, 0x78, 0x22, 0x22, 0x0a, 0x0e, 0x46, 0x69, 0x6e, 0x64, 0x4d, 0x61, 0x78, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x03, 0x6e, 0x75, 0x6d, 0x22, 0x29, 0x0a, 0x0f, 0x46, 0x69, 0x6e, 0x64, 0x4d, 0x61,
	0x78, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x32, 0x54, 0x0a, 0x0e, 0x46, 0x69, 0x6e, 0x64, 0x4d, 0x61, 0x78, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x42, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x4d, 0x61, 0x78, 0x4e, 0x75, 0x6d,
	0x12, 0x17, 0x2e, 0x66, 0x69, 0x6e, 0x64, 0x6d, 0x61, 0x78, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x4d,
	0x61, 0x78, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x66, 0x69, 0x6e, 0x64,
	0x6d, 0x61, 0x78, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x4d, 0x61, 0x78, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x28, 0x01, 0x30, 0x01, 0x42, 0x0c, 0x5a, 0x0a, 0x2f, 0x66, 0x69, 0x6e, 0x64,
	0x6d, 0x61, 0x78, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_findmaxpb_findmax_proto_rawDescOnce sync.Once
	file_findmaxpb_findmax_proto_rawDescData = file_findmaxpb_findmax_proto_rawDesc
)

func file_findmaxpb_findmax_proto_rawDescGZIP() []byte {
	file_findmaxpb_findmax_proto_rawDescOnce.Do(func() {
		file_findmaxpb_findmax_proto_rawDescData = protoimpl.X.CompressGZIP(file_findmaxpb_findmax_proto_rawDescData)
	})
	return file_findmaxpb_findmax_proto_rawDescData
}

var file_findmaxpb_findmax_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_findmaxpb_findmax_proto_goTypes = []interface{}{
	(*FindMaxRequest)(nil),  // 0: findmax.FindMaxRequest
	(*FindMaxResponse)(nil), // 1: findmax.FindMaxResponse
}
var file_findmaxpb_findmax_proto_depIdxs = []int32{
	0, // 0: findmax.FindMaxService.GetMaxNum:input_type -> findmax.FindMaxRequest
	1, // 1: findmax.FindMaxService.GetMaxNum:output_type -> findmax.FindMaxResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_findmaxpb_findmax_proto_init() }
func file_findmaxpb_findmax_proto_init() {
	if File_findmaxpb_findmax_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_findmaxpb_findmax_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindMaxRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_findmaxpb_findmax_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindMaxResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_findmaxpb_findmax_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_findmaxpb_findmax_proto_goTypes,
		DependencyIndexes: file_findmaxpb_findmax_proto_depIdxs,
		MessageInfos:      file_findmaxpb_findmax_proto_msgTypes,
	}.Build()
	File_findmaxpb_findmax_proto = out.File
	file_findmaxpb_findmax_proto_rawDesc = nil
	file_findmaxpb_findmax_proto_goTypes = nil
	file_findmaxpb_findmax_proto_depIdxs = nil
}
